# permissions for end users to view jiratasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jiraops-operator
    app.kubernetes.io/managed-by: kustomize
  name: jiratask-viewer-role
rules:
- apiGroups:
  - jiraops.aspen.com
  resources:
  - jiratasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jiraops.aspen.com
  resources:
  - jiratasks/status
  verbs:
  - get
