# permissions for end users to edit jiratasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jiraops-operator
    app.kubernetes.io/managed-by: kustomize
  name: jiratask-editor-role
rules:
- apiGroups:
  - jiraops.aspen.com
  resources:
  - jiratasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jiraops.aspen.com
  resources:
  - jiratasks/status
  verbs:
  - get
